/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell { 'value' : Value, 'name' : string }
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface FaultRecord {
  'id' : bigint,
  'source' : FaultSource,
  'maintenanceRecommendation' : string,
  'timestamp' : Timestamp,
  'severity' : Severity,
  'faultType' : string,
}
export type FaultSource = { 'injected' : null } |
  { 'detected' : null };
export interface HealthSnapshot {
  'rul' : number,
  'timestamp' : Timestamp,
  'healthScore' : number,
  'confidence' : number,
  'predictedFault' : [] | [string],
}
export type MissionPhase = { 'postLanding' : null } |
  { 'orbit' : null } |
  { 'ascent' : null } |
  { 'launch' : null } |
  { 'reentry' : null } |
  { 'preLaunch' : null } |
  { 'landing' : null };
export interface MissionState {
  'status' : MissionStatus,
  'currentPhase' : MissionPhase,
  'riskLevel' : RiskLevel,
}
export type MissionStatus = { 'aborted' : null } |
  { 'nominal' : null } |
  { 'critical' : null } |
  { 'degraded' : null };
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type RiskLevel = { 'low' : null } |
  { 'high' : null } |
  { 'critical' : null } |
  { 'medium' : null };
export type Severity = { 'low' : null } |
  { 'high' : null } |
  { 'critical' : null } |
  { 'medium' : null };
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'execute' : ActorMethod<[string], Result>,
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFaults' : ActorMethod<[], Array<FaultRecord>>,
  'getHealthHistory' : ActorMethod<[], Array<HealthSnapshot>>,
  'getLatestHealth' : ActorMethod<[], [] | [HealthSnapshot]>,
  'getMissionState' : ActorMethod<[], [] | [MissionState]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordFault' : ActorMethod<[FaultRecord], undefined>,
  'recordHealthSnapshot' : ActorMethod<[HealthSnapshot], undefined>,
  'schema' : ActorMethod<[], string>,
  'setMissionState' : ActorMethod<[MissionState], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];