/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const FaultSource = IDL.Variant({
  'injected' : IDL.Null,
  'detected' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Severity = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'critical' : IDL.Null,
  'medium' : IDL.Null,
});
export const FaultRecord = IDL.Record({
  'id' : IDL.Nat,
  'source' : FaultSource,
  'maintenanceRecommendation' : IDL.Text,
  'timestamp' : Timestamp,
  'severity' : Severity,
  'faultType' : IDL.Text,
});
export const HealthSnapshot = IDL.Record({
  'rul' : IDL.Float64,
  'timestamp' : Timestamp,
  'healthScore' : IDL.Float64,
  'confidence' : IDL.Float64,
  'predictedFault' : IDL.Opt(IDL.Text),
});
export const MissionStatus = IDL.Variant({
  'aborted' : IDL.Null,
  'nominal' : IDL.Null,
  'critical' : IDL.Null,
  'degraded' : IDL.Null,
});
export const MissionPhase = IDL.Variant({
  'postLanding' : IDL.Null,
  'orbit' : IDL.Null,
  'ascent' : IDL.Null,
  'launch' : IDL.Null,
  'reentry' : IDL.Null,
  'preLaunch' : IDL.Null,
  'landing' : IDL.Null,
});
export const RiskLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'critical' : IDL.Null,
  'medium' : IDL.Null,
});
export const MissionState = IDL.Record({
  'status' : MissionStatus,
  'currentPhase' : MissionPhase,
  'riskLevel' : RiskLevel,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFaults' : IDL.Func([], [IDL.Vec(FaultRecord)], ['query']),
  'getHealthHistory' : IDL.Func([], [IDL.Vec(HealthSnapshot)], ['query']),
  'getLatestHealth' : IDL.Func([], [IDL.Opt(HealthSnapshot)], ['query']),
  'getMissionState' : IDL.Func([], [IDL.Opt(MissionState)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordFault' : IDL.Func([FaultRecord], [], []),
  'recordHealthSnapshot' : IDL.Func([HealthSnapshot], [], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'setMissionState' : IDL.Func([MissionState], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const FaultSource = IDL.Variant({
    'injected' : IDL.Null,
    'detected' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Severity = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'critical' : IDL.Null,
    'medium' : IDL.Null,
  });
  const FaultRecord = IDL.Record({
    'id' : IDL.Nat,
    'source' : FaultSource,
    'maintenanceRecommendation' : IDL.Text,
    'timestamp' : Timestamp,
    'severity' : Severity,
    'faultType' : IDL.Text,
  });
  const HealthSnapshot = IDL.Record({
    'rul' : IDL.Float64,
    'timestamp' : Timestamp,
    'healthScore' : IDL.Float64,
    'confidence' : IDL.Float64,
    'predictedFault' : IDL.Opt(IDL.Text),
  });
  const MissionStatus = IDL.Variant({
    'aborted' : IDL.Null,
    'nominal' : IDL.Null,
    'critical' : IDL.Null,
    'degraded' : IDL.Null,
  });
  const MissionPhase = IDL.Variant({
    'postLanding' : IDL.Null,
    'orbit' : IDL.Null,
    'ascent' : IDL.Null,
    'launch' : IDL.Null,
    'reentry' : IDL.Null,
    'preLaunch' : IDL.Null,
    'landing' : IDL.Null,
  });
  const RiskLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'critical' : IDL.Null,
    'medium' : IDL.Null,
  });
  const MissionState = IDL.Record({
    'status' : MissionStatus,
    'currentPhase' : MissionPhase,
    'riskLevel' : RiskLevel,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFaults' : IDL.Func([], [IDL.Vec(FaultRecord)], ['query']),
    'getHealthHistory' : IDL.Func([], [IDL.Vec(HealthSnapshot)], ['query']),
    'getLatestHealth' : IDL.Func([], [IDL.Opt(HealthSnapshot)], ['query']),
    'getMissionState' : IDL.Func([], [IDL.Opt(MissionState)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordFault' : IDL.Func([FaultRecord], [], []),
    'recordHealthSnapshot' : IDL.Func([HealthSnapshot], [], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'setMissionState' : IDL.Func([MissionState], [], []),
  });
};

export const init = ({ IDL }) => { return []; };